# Use "Basically Basic" theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-US
title: EmmetCoughlan.com
email: admin@emmetcoughlan.com
description: ""
baseurl: ""
url: "https://www.emmetcoughlan.com"
logo: /assets/logos/logo-emmet-space.webp

# Author Info
author:
  name: Emmet Coughlan
  twitter: lordemmet
  picture: /assets/images/emmet-coughlan.jpg

# Social Media
socials:
  github: EccTM
  trakt: ecctm
  twitter: lordemmet
  youtube: lordemmet

# Search Settings
search: true
search_full_content: true
search_provider: lunr
#algolia:
#  application_id:      # YOUR_APPLICATION_ID
#  index_name:          # YOUR_INDEX_NAME
#  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#  powered_by:          # true (default), false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
timezone: Europe/London

# Plugins (previously 'gems')
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      read_time: true
