title: Emmet Coughlan
description: Development / Gaming / Music 
name: Emmet Coughlan
email: admin@emmetcoughlan.com
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

author:
  name: Emmet Coughlan
  twitter: Lordemmet
  picture:
twitter_username: Lordemmet
github_username: EccTM
