title: Emmet Coughlan
description: Development / Gaming / Music 
name: EccTM
email: admin@emmetcoughlan.com
theme: minima

minima:
  social_links:
    twitter: Lordemmet
    github: EccTM
    youtube_channel: UCqsLqIJzoQqMOOHbwj1pOeg
