title: Emmet Coughlan
description: Development / Gaming / Music 
name: EccTM
email: admin@emmetcoughlan.com

minima:
  skin: dark

  social_links:
    twitter: Lordemmet
    github: EccTM
    youtube_channel: UCqsLqIJzoQqMOOHbwj1pOeg

header_pages:

theme: minima
