# Use "Basically Basic" theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-US
title: EmmetCoughlan.com
email: admin@emmetcoughlan.com
description: Development / Gaming / Music 
baseurl: ""  # subpath: /blog
url: "https://www.emmetcoughlan.com" # base hostname & protocol: https://example.com
author:
  name: Emmet Coughlan
  twitter: Lordemmet
  picture: /assets/images/johndoe.png
twitter_username: Lordemmet
github_username: EccTM
logo: /assets/icons/basically-basic-logo-dark.svg
search: true
search_full_content: true
search_provider: lunr

# Outputting
permalink: /:categories/:title/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      read_time: true
